version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=root:password@tcp(db:3306)/superindo?charset=utf8mb4&parseTime=True&loc=Local

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: superindo

  redis:
    image: redis:6